name: Release

on:
  create:
    branches: 
      - release/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore
        run: nuget restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
